//
// Created by kir on 01.10.2025.
//

#ifndef VISMUT_ERRORS_H
#define VISMUT_ERRORS_H
#include <errno.h>

#define VISMUT_ERRORS_START 0xffff

typedef enum {
    VISMUT_ERROR_OK = 0,
    VISMUT_ERROR_ALLOC = VISMUT_ERRORS_START + 1,
    VISMUT_ERROR_ENCODING,
    VISMUT_ERROR_IO,
    VISMUT_ERROR_BUFFER_OVERFLOW,
    VISMUT_ERROR_UNKNOWN_NUMBER_FORMAT,
    VISMUT_ERROR_UNKNOWN_CHAR,
    VISMUT_ERROR_NUMBER_OVERFLOW,
    VISMUT_ERROR_NUMBER_PARSE,
    VISMUT_ERROR_UNEXPECTED_TOKEN,
    VISMUT_ERROR_SYMBOL_ALREADY_DEFINED,
    VISMUT_ERROR_SYMBOL_NOT_DEFINED,
    VISMUT_ERROR_UNSUPPORTED_OPERATION,
    VISMUT_ERROR_TYPE_IS_INCOMPATIBLE,
    VISMUT_ERROR_CAST_IS_NOT_ALLOWED,
    VISMUT_ERROR_UNKNOWN_TYPE,
    VISMUT_ERROR_COUNT
} VismutError;

typedef struct {
    VismutError error;
} VismutErrorInfo;

const char *GetErrorString(errno_t);

#endif //VISMUT_ERRORS_H
